/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tela;

import classes.Equipamento;
import classes.Radio;
import classes.TV;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;

/**
 *
 * @author Murilo
 */
public class Menu extends javax.swing.JFrame {
    private Equipamento objEquipamento;
    
    private void limparCampos() {
        tMarca.setText(null);
        tModelo.setText(null);
        tTela.setText(null);
        
        lbCanal.setText("Canal:");
        lbEstado.setText("Estado:");
        lbVolume.setText("Volume:");
        
        bAmFm.setText("AM");
        btIniciar.setEnabled(true);
        bLigar.setText("Ligar");
        
        cbVolts.setSelectedIndex(0);
    }
    
    public Menu() {
        initComponents();
        rbgroup.add(rbTV);
        rbgroup.add(rbRadio);
        
        rbTV.setSelected(true);
        rbRadio.setSelected(false);
        bAmFm.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Equipamento");
        this.setResizable(false);
        
        bCHMais.setEnabled(false);
        bCHMenos.setEnabled(false);
        bVolMais.setEnabled(false);
        bVolMenos.setEnabled(false);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbgroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tModelo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tMarca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bLigar = new javax.swing.JButton();
        bLimpar = new javax.swing.JButton();
        bSair = new javax.swing.JButton();
        bCHMais = new javax.swing.JButton();
        bCHMenos = new javax.swing.JButton();
        rbRadio = new javax.swing.JRadioButton();
        cbVolts = new javax.swing.JComboBox();
        bVolMais = new javax.swing.JButton();
        bVolMenos = new javax.swing.JButton();
        pEquipamento = new javax.swing.JPanel();
        lbEstado = new javax.swing.JLabel();
        lbCanal = new javax.swing.JLabel();
        lbVolume = new javax.swing.JLabel();
        tTela = new javax.swing.JTextField();
        lbTela = new javax.swing.JLabel();
        bAmFm = new javax.swing.JButton();
        btIniciar = new javax.swing.JButton();
        rbTV = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Modelo");

        jLabel2.setText("Marca");

        jLabel3.setText("Voltagem");

        bLigar.setText("Ligar");
        bLigar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLigarActionPerformed(evt);
            }
        });

        bLimpar.setText("Limpar Campos");
        bLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimparActionPerformed(evt);
            }
        });

        bSair.setText("Sair");
        bSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairActionPerformed(evt);
            }
        });

        bCHMais.setText("CH +");
        bCHMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCHMaisActionPerformed(evt);
            }
        });

        bCHMenos.setText("CH -");
        bCHMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCHMenosActionPerformed(evt);
            }
        });

        rbRadio.setText("Radio");
        rbRadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbRadioStateChanged(evt);
            }
        });

        cbVolts.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "110V", "220V", "Bivolt" }));

        bVolMais.setText("Vol +");
        bVolMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolMaisActionPerformed(evt);
            }
        });

        bVolMenos.setText("Vol -");
        bVolMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolMenosActionPerformed(evt);
            }
        });

        pEquipamento.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Equipamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 0, 255))); // NOI18N
        pEquipamento.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N

        lbEstado.setText("Estado:");

        lbCanal.setText("Canal:");

        lbVolume.setText("Volume:");

        lbTela.setText("Tela:");

        bAmFm.setText("AM");
        bAmFm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAmFmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pEquipamentoLayout = new javax.swing.GroupLayout(pEquipamento);
        pEquipamento.setLayout(pEquipamentoLayout);
        pEquipamentoLayout.setHorizontalGroup(
            pEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEquipamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pEquipamentoLayout.createSequentialGroup()
                        .addComponent(lbEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 363, Short.MAX_VALUE)
                        .addComponent(lbTela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tTela, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pEquipamentoLayout.createSequentialGroup()
                        .addComponent(lbVolume)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pEquipamentoLayout.createSequentialGroup()
                        .addComponent(lbCanal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bAmFm)))
                .addGap(32, 32, 32))
        );
        pEquipamentoLayout.setVerticalGroup(
            pEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEquipamentoLayout.createSequentialGroup()
                .addGroup(pEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pEquipamentoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbEstado))
                    .addGroup(pEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbTela)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAmFm)
                    .addComponent(lbCanal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbVolume)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btIniciar.setText("Iniciar");
        btIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIniciarActionPerformed(evt);
            }
        });

        rbTV.setText("TV");
        rbTV.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbTVItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rbTV)
                            .addGap(29, 29, 29)
                            .addComponent(rbRadio)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel2))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bLigar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(bCHMais)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bCHMenos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bVolMais))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(tMarca)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(bVolMenos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bLimpar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bSair))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbVolts, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(11, 11, 11)))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbVolts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btIniciar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLigar)
                    .addComponent(bLimpar)
                    .addComponent(bSair)
                    .addComponent(bCHMais)
                    .addComponent(bCHMenos)
                    .addComponent(bVolMais)
                    .addComponent(bVolMenos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbRadio)
                    .addComponent(rbTV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIniciarActionPerformed
        if (rbTV.isSelected()) {
            int tela = 0;
            
            try {
                tela = Integer.parseInt(tTela.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Tamanho da tela inválido.", "Equipamento", 0);
                return;
            }
                
            objEquipamento = new TV(tModelo.getText(), tMarca.getText(), (String)(cbVolts.getItemAt(cbVolts.getSelectedIndex())), tela);
        }
        else if(rbRadio.isSelected()) {            
            objEquipamento = new Radio(tModelo.getText(), tMarca.getText(), (String) cbVolts.getItemAt(cbVolts.getSelectedIndex()));
            
        }
        lbEstado.setText("Estado: desligado");
        
        btIniciar.setEnabled(false);
    }//GEN-LAST:event_btIniciarActionPerformed

    private void bLigarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLigarActionPerformed
        if (objEquipamento.isLigado()) {
            lbEstado.setText("Estado: " + objEquipamento.desligar());
            lbVolume.setText("Volume:");
            lbCanal.setText("Canal:");
            bLigar.setText("Ligar");
        } else {
            lbEstado.setText("Estado: " + objEquipamento.ligar());
            lbVolume.setText("Volume: " + objEquipamento.getVolume());
            lbCanal.setText("Canal: " + objEquipamento.getCanal());
            bLigar.setText("Desligar");
        }
        
        bCHMais.setEnabled(objEquipamento.isLigado());
        bCHMenos.setEnabled(objEquipamento.isLigado());
        bVolMais.setEnabled(objEquipamento.isLigado());
        bVolMenos.setEnabled(objEquipamento.isLigado());
    }//GEN-LAST:event_bLigarActionPerformed

    private void rbTVItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbTVItemStateChanged
        lbTela.setVisible(rbTV.isSelected());
        tTela.setVisible(rbTV.isSelected());
    }//GEN-LAST:event_rbTVItemStateChanged

    private void rbRadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbRadioStateChanged
        bAmFm.setVisible(rbRadio.isSelected());
    }//GEN-LAST:event_rbRadioStateChanged

    private void bCHMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCHMaisActionPerformed
        objEquipamento.mudarCanalMais();
        lbCanal.setText("Canal: " + objEquipamento.getCanal());
    }//GEN-LAST:event_bCHMaisActionPerformed

    private void bCHMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCHMenosActionPerformed
        objEquipamento.mudarCanalMenos();
        lbCanal.setText("Canal: " + objEquipamento.getCanal());
    }//GEN-LAST:event_bCHMenosActionPerformed

    private void bVolMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolMaisActionPerformed
        objEquipamento.aumentarVolume();
        lbVolume.setText("Volume: " + objEquipamento.getVolume());
    }//GEN-LAST:event_bVolMaisActionPerformed

    private void bVolMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolMenosActionPerformed
        objEquipamento.dimiuirVolume();
        lbVolume.setText("Volume: " + objEquipamento.getVolume());
    }//GEN-LAST:event_bVolMenosActionPerformed

    private void bSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairActionPerformed
        System.exit(1);
    }//GEN-LAST:event_bSairActionPerformed

    private void bAmFmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAmFmActionPerformed
        objEquipamento.mudarAM_FM();
        if (objEquipamento.getAmFm() == 0) {
            bAmFm.setText("AM");
        } else {
            bAmFm.setText("FM");
        }
        
        lbCanal.setText("Canal: " + objEquipamento.getCanal());
    }//GEN-LAST:event_bAmFmActionPerformed

    private void bLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_bLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAmFm;
    private javax.swing.JButton bCHMais;
    private javax.swing.JButton bCHMenos;
    private javax.swing.JButton bLigar;
    private javax.swing.JButton bLimpar;
    private javax.swing.JButton bSair;
    private javax.swing.JButton bVolMais;
    private javax.swing.JButton bVolMenos;
    private javax.swing.JButton btIniciar;
    private javax.swing.JComboBox cbVolts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbCanal;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbTela;
    private javax.swing.JLabel lbVolume;
    private javax.swing.JPanel pEquipamento;
    private javax.swing.JRadioButton rbRadio;
    private javax.swing.JRadioButton rbTV;
    private javax.swing.ButtonGroup rbgroup;
    private javax.swing.JTextField tMarca;
    private javax.swing.JTextField tModelo;
    private javax.swing.JTextField tTela;
    // End of variables declaration//GEN-END:variables
}
