package telaMenu;

import classes.Carro;
import classes.Chevrolet;
import classes.Lotus;
import classes.Vendedor;
import classes.Volvo;
import java.awt.Color;
import java.net.URL;
import javax.swing.JOptionPane;

public class Menu extends javax.swing.JFrame {
    
    private Carro objCarro;
    private Vendedor objVendedor = new Vendedor();
    
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Nigro's Car");
        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/chevrolet.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tAno = new javax.swing.JTextField();
        tValor = new javax.swing.JTextField();
        cbMarca = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tComissao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tComissaoGeral = new javax.swing.JTextField();
        bComissao = new javax.swing.JButton();
        bPagar = new javax.swing.JButton();
        bLimpar = new javax.swing.JButton();
        tModelo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Modelo:");

        jLabel2.setText("Ano:");

        jLabel3.setText("Valor: R$");

        cbMarca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chevrolet", "Lotus", "Volvo" }));
        cbMarca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMarcaItemStateChanged(evt);
            }
        });

        jLabel4.setText("Marca:");

        jLabel5.setText("Logotipo:");

        jLabel7.setText("Comissão: R$");

        tComissao.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tComissao.setText("0.00");

        jLabel8.setText("Comissão Total: R$");

        tComissaoGeral.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tComissaoGeral.setText("0.00");

        bComissao.setText("Comissão");
        bComissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bComissaoActionPerformed(evt);
            }
        });

        bPagar.setText("Pagar Comissão");
        bPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPagarActionPerformed(evt);
            }
        });

        bLimpar.setText("L");
        bLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(tComissao))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tComissaoGeral))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bComissao)
                                .addGap(18, 18, 18)
                                .addComponent(bPagar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bLimpar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(14, 14, 14)
                                        .addComponent(cbMarca, 0, 144, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tValor, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                            .addComponent(tAno)
                                            .addComponent(tModelo))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tComissaoGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bComissao)
                    .addComponent(bPagar)
                    .addComponent(bLimpar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bComissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bComissaoActionPerformed
        if (tModelo.getText().trim().equals("")){
            tModelo.setBackground(Color.yellow);
            return;
        }
        
        if (tAno.getText().trim().equals("")){
            tAno.setBackground(Color.yellow);
            return;
        }
        
        if (tValor.getText().trim().equals("")){
            tValor.setBackground(Color.yellow);
            return;
        }
        
        double valor;
        
        try {
            valor = Float.parseFloat(tValor.getText());
        } catch (NumberFormatException e ) {
            JOptionPane.showMessageDialog(rootPane, "Poxa, voce inseriu um valor invalido, tente de novo!", "Erro", 0);
            tValor.setBackground(Color.yellow);
            return;
        }
        
        if (cbMarca.getSelectedIndex() == 0) {
            objCarro = new Chevrolet();
        }
        else if (cbMarca.getSelectedIndex() == 1) {
            objCarro = new Lotus();
        }
        else {
            objCarro = new Volvo();
        }
               
        objCarro.setAno(tAno.getText());
        objCarro.setModelo(tModelo.getText());
        objCarro.setValor(valor);
        
        double comissao = objCarro.gerarComissao();
        
        tComissao.setText(String.format("%.2f", comissao));
        
        objVendedor.calculoComissao(comissao);
        
        tComissaoGeral.setText(String.format("%.2f",objVendedor.getComissaoMensal()));
        
        tModelo.setText("");
        tAno.setText("");
        tValor.setText("");
        
        objCarro = null;
    }//GEN-LAST:event_bComissaoActionPerformed

    private void bLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimparActionPerformed
        tModelo.setText("");
        tAno.setText("");
        tValor.setText("");
        tComissao.setText("0.00");
        tComissaoGeral.setText("0.00");
        cbMarca.setSelectedIndex(0);
        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/chevrolet.jpg")));
        tAno.setBackground(Color.WHITE);
        tValor.setBackground(Color.WHITE);
        tModelo.setBackground(Color.WHITE);
    }//GEN-LAST:event_bLimparActionPerformed

    private void cbMarcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMarcaItemStateChanged
        if (cbMarca.getSelectedIndex() == 0) {
            imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/chevrolet.jpg")));
        }
        else if (cbMarca.getSelectedIndex() == 1) {
            imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/lotus.jpg")));
        }
        else if (cbMarca.getSelectedIndex() == 2) {
            imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/volvo.jpg")));
        }
        else            
            imgLogo.setIcon(null);        
    }//GEN-LAST:event_cbMarcaItemStateChanged

    private void bPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPagarActionPerformed
        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/dinheiro.gif")));
    }//GEN-LAST:event_bPagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bComissao;
    private javax.swing.JButton bLimpar;
    private javax.swing.JButton bPagar;
    private javax.swing.JComboBox cbMarca;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField tAno;
    private javax.swing.JTextField tComissao;
    private javax.swing.JTextField tComissaoGeral;
    private javax.swing.JTextField tModelo;
    private javax.swing.JTextField tValor;
    // End of variables declaration//GEN-END:variables
}
